apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uber-eat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-force-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - uber-eat.mydigitalschool.server.dylanbattig.fr
      secretName: uber-eat-tls
  rules:
    - host: uber-eat.mydigitalschool.server.dylanbattig.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uber-eat
                port:
                  name: http