apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases
  - ingress.yaml
images:
  - name: uber_eat_image
    newName: "harbor.server.dylanbattig.fr/private/uber_eat" # {"$imagepolicy": "flux-system:uber-eat:name"}
    newTag: "main-7e643f2d261fb72e6a8086d2031adbb1133cc7d4-4" # {"$imagepolicy": "flux-system:uber-eat:tag"}
